pipeline {
  agent any

  options {
    timestamps()
    buildDiscarder(logRotator(numToKeepStr: '20'))
  }

  stages {

    stage('Build') {
      steps {
        sh '''
          rm -rf report
          mkdir -p report

          cat > report/index.html <<'EOF'
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Hello from Jenkins</title>
  <style>
    body{margin:0;height:100vh;display:grid;place-items:center;background:#0b1220;color:#e9eefc;font-family:Arial}
    .card{width:min(720px,92%);padding:28px;border-radius:18px;background:rgba(255,255,255,.08);
          border:1px solid rgba(255,255,255,.15);box-shadow:0 16px 40px rgba(0,0,0,.35);text-align:center}
    h1{margin:0 0 10px;font-size:36px}
    p{margin:0 0 18px;color:rgba(233,238,252,.75)}
    .btns{display:flex;justify-content:center;gap:10px;flex-wrap:wrap}
    button{padding:10px 14px;border-radius:12px;border:0;cursor:pointer;font-weight:700}
    .primary{background:linear-gradient(135deg,#5eead4,#60a5fa);color:#06101c}
    .ghost{background:rgba(255,255,255,.12);color:#e9eefc;border:1px solid rgba(255,255,255,.2)}
    .small{margin-top:14px;font-size:12px;color:rgba(233,238,252,.55)}
    code{background:rgba(0,0,0,.25);padding:2px 6px;border-radius:10px;border:1px solid rgba(255,255,255,.12)}
  </style>
</head>
<body>
  <div class="card">
    <h1>Hello from Jenkins ✅</h1>
    <p>This is a styled HTML artifact generated by the pipeline.</p>
    <div class="btns">
      <button class="primary" onclick="alert('Build Successful ✅')">Click Me</button>
      <button class="ghost" onclick="document.body.style.background='#111827'">Change Theme</button>
      <button class="ghost" onclick="navigator.clipboard.writeText('Hello from Jenkins')">Copy Text</button>
    </div>
    <div class="small">Generated by Jenkins • File: <code>report/index.html</code></div>
  </div>
</body>
</html>
EOF
        '''
      }
    }

    stage('Test') {
      steps {
        sh '''
          test -f report/index.html
          grep -q "Hello from Jenkins" report/index.html
        '''
      }
    }

    stage('Deploy') {
      steps {
        // "Deploy" here means: store as artifact you can open/download
        archiveArtifacts artifacts: 'report/index.html', fingerprint: true
        echo "Go to: Build -> Artifacts -> report/index.html"
      }
    }
  }

  post {
    always { cleanWs() }
  }
}
